<testsuite name="amazonearbuds.search for best earbuds in amazon" tests="1" errors="1" failures="0" skipped="0" time="0.015412" timestamp="2022-07-13T18:17:37.924779" hostname="IBS-LAP-482"><testcase classname="amazonearbuds.search for best earbuds in amazon" name="user search for earbuds in amazon -- @1.1 " status="failed" time="0.015412"><error type="Error" message="net::ERR_INTERNET_DISCONNECTED at https://www.amazon.in/&#10;=========================== logs ===========================&#10;navigating to &quot;https://www.amazon.in/&quot;, waiting until &quot;load&quot;&#10;============================================================">
<![CDATA[
Failing step: Given user is on "https://www.amazon.in/" ... failed in 0.015s
Location: amazonearbuds.feature:4
Traceback (most recent call last):
  File "C:\Users\suhas.kunchala\.virtualenvs\BehavePlaywrightDemo-iLd2CAUR\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\suhas.kunchala\.virtualenvs\BehavePlaywrightDemo-iLd2CAUR\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "steps\uploadfile_TC_105.py", line 8, in step_impl
    context.imgbbhome.imgbbsite(website)
  File "D:\ImpressicoProjects\BehavePlaywrightDemo\PageObjects\imgbb\Imgbb_Homepage.py", line 27, in imgbbsite
    self.driver.visturl(url)
  File "D:\ImpressicoProjects\BehavePlaywrightDemo\helpers\helper_base.py", line 177, in visturl
    self._page.goto(url)
  File "C:\Users\suhas.kunchala\.virtualenvs\BehavePlaywrightDemo-iLd2CAUR\lib\site-packages\playwright\sync_api\_generated.py", line 7393, in goto
    self._sync(
  File "C:\Users\suhas.kunchala\.virtualenvs\BehavePlaywrightDemo-iLd2CAUR\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "C:\Users\suhas.kunchala\.virtualenvs\BehavePlaywrightDemo-iLd2CAUR\lib\site-packages\playwright\_impl\_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\suhas.kunchala\.virtualenvs\BehavePlaywrightDemo-iLd2CAUR\lib\site-packages\playwright\_impl\_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\suhas.kunchala\.virtualenvs\BehavePlaywrightDemo-iLd2CAUR\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\suhas.kunchala\.virtualenvs\BehavePlaywrightDemo-iLd2CAUR\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_INTERNET_DISCONNECTED at https://www.amazon.in/
=========================== logs ===========================
navigating to "https://www.amazon.in/", waiting until "load"
============================================================
]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario Outline: user search for earbuds in amazon -- @1.1 
    Given user is on "https://www.amazon.in/" ... failed in 0.015s
    Then user search for earbuds ... undefined in 0.000s
    And user checks with microphone and wireless box ... undefined in 0.000s
    Then open each earbud link ... undefined in 0.000s
    Then get required data ... undefined in 0.000s
    Then connect to database ... undefined in 0.000s
    And update data in table ... undefined in 0.000s

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>